version: "3"
services:
  app:
    build:
      context: ./user-service
    working_dir: /user-service
    volumes:
      - ./user-service:/user-service
    expose:
      - 8080
    ports:
      - 8080:8080
    command: mvn -X -e spring-boot:run
    depends_on:
      - mongodb
    network_mode: host

  mongodb:
    container_name: mongodbContainer
    image: mongo:4.2.3
    restart: on-failure
    ports:
      - 27017:27017