version: "3"
services:
  app:
    image: user-service
 #   build: ./user-service/.
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    network_mode: host

  mongodb:
    container_name: mongodbContainer
    image: mongo:4.2.3
    restart: on-failure
    ports:
      - 27017:27017