FROM openjdk:latest

LABEL maintainer="sayeddev@yahoo.com"
VOLUME /tmp

EXPOSE 8080

ARG JAR_FILE=target/api-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} api.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/api.jar"]